Source/TeamMashup.Server/Areas/Internal/Controllers/BillingController.cs
using Microsoft.Web.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using TeamMashup.Core;
using TeamMashup.Core.Contracts;
using TeamMashup.Core.Domain;
using TeamMashup.Models.Internal;
using TeamMashup.Server.Filters;

namespace TeamMashup.Server.Areas.Internal.Controllers
{
    [NoCache]
    public class BillingController : InternalBaseController
    {
        public ActionResult Index()
        {
            return View("Subscriptions");
        }

        public ActionResult GetSubscriptions(int iDisplayStart, int iDisplayLength, string sEcho)
        {

            var query = Context.Subscriptions.OrderByDescending(x => x.TenantName);

            var totalRecords = query.Count();

            var page = query.Skip(iDisplayStart).Take(iDisplayLength).ToList();

            var model = new DataTablePage
            {
                sEcho = sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords
            };

            var subscriptions = (from x in page
                                 select new SubscriptionsBillingModel
                                 {
                                     Id = x.Id,
                                     TenantName = x.TenantName,
                                     CompanyName = x.CompanyName,
                                     CountryName = x.Country.Name,
                                     PlanName = x.SubscriptionPlan.Name,
                                     State = x.State.ToString()
                                 }).ToList();

            foreach (var subscription in subscriptions)
            {
                var item = new Dictionary<string, string>
                    {
                        {"TenantName", subscription.TenantName},
                        {"CompanyName", subscription.CompanyName},
                        {"CountryName", subscription.CountryName},
                        {"PlanName", subscription.PlanName},
                        {"State", subscription.State},
                        {"HasPendingBills", subscription.HasPendingBills.AsYesNo()},
                        {"DT_RowId", "roleItem_" + subscription.Id}
                    };

                model.aaData.Add(item);
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(string tenantName)
        {
            Subscription subscription;
            if (!Context.Subscriptions.TryGetByTenantName(tenantName, out subscription))
                throw new ApplicationException("Subscription with TenantName = " + tenantName + " does not exist");

            var bills = Context.Bills.FilterBySubscription(subscription.Id).ToList();

            var model = new BillingDetailsModel
            {
                TenantName = tenantName,
                SubscriptionId = subscription.Id,
                Bills = (from x in bills
                         select new BillModel
                         {
                             Id = x.Id,
                             CountryName = x.CustomerCountry.Name,
                             CustomerAddress = x.CustomerAddress,
                             CustomerName = x.CustomerName,
                             Date = x.Date,
                             TributaryId = x.TributaryId,
                             Items = (from y in x.Items
                                      select new BillItemModel
                                      {
                                          Price = y.Price,
                                          Description = y.Description,
                                          Quantity = y.Quantity
                                      }).ToList()
                         }).ToList()
            };

            return View(model);
        }


        public ActionResult Bill(long id)
        {
            Bill bill;
            if (!Context.Bills.TryGetById(id, out bill))
                throw new InvalidOperationException("Cannot find bill with Id " + id + " was not found");

            var type = bill.CustomerCountry.Name == Constants.LocalCountryName ? "A" : "E";
            var model = new BillModel
            {
                Id = bill.Id,
                Type = type,
                CountryName = bill.CustomerCountry.Name,
                CustomerAddress = bill.CustomerAddress,
                CustomerName = bill.CustomerName,
                Date = bill.Date,
                TributaryId = bill.TributaryId,
                Items = (from y in bill.Items
                         select new BillItemModel
                         {
                             Price = y.Price,
                             Description = y.Description,
                             Quantity = y.Quantity
                         }).ToList()
            };

            return View(model);
        }

        public ActionResult Reports(long? from, long? to)
        {
            DateTime dateFrom, dateTo;

            if (!from.HasValue)
                dateFrom = DateTime.UtcNow.AddMonths(-1);
            else
                dateFrom = DateTimeExtensions.Epoch.AddSeconds(from.Value);

            if (!to.HasValue)
                dateTo = DateTime.UtcNow;
            else
                dateTo = DateTimeExtensions.Epoch.AddSeconds(to.Value);


            var query = from b in Context.Bills
                        where b.Date >= dateFrom && b.Date <= dateTo
                        orderby b.Date descending
                        select b;

            var bills = (from x in query
                         select new BillingSummaryModel
                         {
                             BillId = x.Id,
                             Date = x.Date,
                             CustomerName = x.CustomerName,
                             TributaryId = x.TributaryId,
                             Total = x.Items.Sum(y => y.Quantity * y.Price)
                         }).ToList();

            decimal totalBilled = 0;
            
            if(Context.Bills.Any())
            {
                totalBilled = (from b in Context.Bills
                               where b.Date >= dateFrom && b.Date <= dateTo
                               select b).Sum(x => x.Items.Select(y => y.Price * y.Quantity).Sum());
            }

            var model = new BillingReportModel
            {
                TotalBilled = totalBilled,
                Bills = bills
            };

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult PeriodFilter()
        {
            return PartialView("_PeriodFilter");
        }

        public ActionResult ExportBilledToExcel(long? from, long? to)
        {
            DateTime dateFrom, dateTo;

            if (!from.HasValue)
                dateFrom = DateTime.UtcNow.AddMonths(-1);
            else
                dateFrom = DateTimeExtensions.Epoch.AddSeconds(from.Value);

            if (!to.HasValue)
                dateTo = DateTime.UtcNow;
            else
                dateTo = DateTimeExtensions.Epoch.AddSeconds(to.Value);


            var query = from b in Context.Bills
                        where b.Date >= dateFrom && b.Date <= dateTo
                        orderby b.Date descending
                        select b;

            var bills = (from x in query
                         select new BillingSummaryModel
                         {
                             BillId = x.Id,
                             Date = x.Date,
                             CustomerName = x.CustomerName,
                             TributaryId = x.TributaryId,
                             Total = x.Items.Sum(y => y.Quantity * y.Price)
                         }).ToList();

            if (bills.Any())
            {
                var gv = new GridView();
                gv.DataSource = bills.ToList();
                gv.DataBind();
                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename=Billing.xls");
                Response.ContentType = "application/ms-excel";
                Response.Charset = "";
                var sw = new StringWriter();
                var htw = new HtmlTextWriter(sw);
                gv.RenderControl(htw);
                Response.Output.Write(sw.ToString());
                Response.Flush();
                Response.End();
            }

            return this.RedirectToAction<BillingController>(x => x.Reports(from, to));
        }
    }
}

Source/TeamMashup.Server/Areas/Private/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using TeamMashup.Core.Domain;
using TeamMashup.Core.Enums;
using TeamMashup.Models;
using TeamMashup.Models.Admin;
using TeamMashup.Models.Private;

namespace TeamMashup.Server.Areas.Private.Controllers
{
    public class ReportsController : ProjectBaseController
    {
        public ActionResult Index()
        {
            var model = new BurndownModel();

            Iteration iteration;
            var anIterationIsActive = ProjectContext.Iterations.TryGetActive(out iteration);

            ViewBag.ShowReports = anIterationIsActive;

            if (anIterationIsActive)
            {
                var startOfIteration = iteration.From.Date;
                var endOfIteration = iteration.To.Date;

                var issueProgress = (from x in ProjectContext.IssueProgresses
                                     where x.IterationId == iteration.Id
                                     select x).ToList();

                var startOfIterationStoryPoints = (from x in issueProgress
                                                   where x.Type == IssueProgressType.IterationStarted
                                                   select x).Sum(x => x.StoryPoints);

                var issueProgressByDay = from x in issueProgress
                                         group x by x.Date.Date into g
                                         select new { Date = g.Key, Changes = g.ToList() };

                var previousDayStoryPoints = 0;
                var storyPointsByDay = new Dictionary<DateTime, int> {{startOfIteration, startOfIterationStoryPoints}};

                foreach (var item in issueProgressByDay)
                {
                    previousDayStoryPoints = previousDayStoryPoints + item.Changes.Sum(x => x.StoryPoints);
                    storyPointsByDay.Add(item.Date.AddDays(1), previousDayStoryPoints);
                }

                var builder = new StringBuilder();
                foreach (var sp in storyPointsByDay)
                {
                    builder.Append(string.Format("[{0},{1}],", sp.Key.GetMillisecondsFromEpoch(), sp.Value));
                }

                var start = startOfIteration.GetMillisecondsFromEpoch();
                var end = endOfIteration.GetMillisecondsFromEpoch();

                model.DataSets = new List<DataSet>
                {
                    new DataSet 
                    { 
                        Key="ideal",
                        Label = "Ideal",
                        Data = string.Format("[[{0},{1}],[{2},{3}]]", start, startOfIterationStoryPoints, end, 0)
                    },
                    new DataSet 
                    { 
                        Key="open",
                        Label = "Open Story Points",
                        Data = string.Format("[{0}]",
                        builder.ToString().TrimEnd(','))
                    }
                };
            }


            return View("Burndown", model);
        }

        public ActionResult Iteration(long? releaseId, long? iterationId)
        {
            var model = new IterationReportModel();
            ViewBag.ShowReports = false;

            Iteration iteration;
            var anIterationIsActive = ProjectContext.Iterations.TryGetActive(out iteration);

            if (!releaseId.HasValue)
            {
                long rId;
                if (anIterationIsActive)
                {
                    releaseId = iteration.ReleaseId;
                }
                else
                {
                    if (TryGetMostRecentSelectableReleaseId(out rId, mustHaveIterations: true))
                        releaseId = rId;
                }
            }

            if (releaseId.HasValue)
                ViewBag.ReleaseId = releaseId.Value;

            if (releaseId.HasValue && !iterationId.HasValue)
            {
                long iId;
                if (anIterationIsActive)
                {
                    iterationId = iteration.Id;
                }
                else
                {
                    if (TryGetMostRecentSelectableIterationId(releaseId.Value, out iId))
                        iterationId = iId;
                }
            }

            if (iterationId.HasValue)
            {
                ViewBag.IterationId = iterationId.Value;
                ViewBag.ShowReports = true;

                model.IterationId = iterationId.Value;

                var issues = ProjectContext.GetIterationIssues(iterationId.Value);

                model.Commited = issues.Sum(x => x.StoryPoints);
                model.Completed = (from x in issues
                                   where x.State == ScheduleState.Done
                                   select x.StoryPoints).Sum();

                var issuesByUser = (from x in issues
                                    where x.Assignee != null
                                    group x by x.Assignee into g
                                    select g).ToList();

                model.UserStats = (from x in issuesByUser
                                   select new Tuple<UserModel, IterationIssueStats>(new UserModel
                                   {
                                       Id = x.Key.Id,
                                       Name = x.Key.Name,
                                   },
                                   new IterationIssueStats
                                   {
                                       DefinedPoints = (from y in x
                                                        where y.State == ScheduleState.Defined
                                                        select y.StoryPoints).Sum(),
                                       DonePoints = (from y in x
                                                     where y.State == ScheduleState.Done
                                                     select y.StoryPoints).Sum(),
                                       InProgressPoints = (from y in x
                                                           where y.State == ScheduleState.InProgress
                                                           select y.StoryPoints).Sum()
                                   })).ToList();
            }

            return View("Iteration", model);
        }
    }
}

Source/TeamMashup.Server/Areas/Internal/Views/Billing/Bill.cshtml
@model TeamMashup.Models.Internal.BillModel

@{
    ViewBag.Title = "Bill";
    Layout = "~/Views/Shared/_Printable.cshtml";
}

<div id="billing">
    <div class="container bill">
        <div class="row header">
            <div class="col-xs-5 left-aside">
                <h4>TeamMashup S.R.L</h4>
                <p>Av. Córdoba XXXX 1A (1427) Capital Federal</p>
                <p>Responsable Inscripto</p>
            </div>
            <div class="col-xs-2 type">
                <h1>@Model.Type</h1>
            </div>
            <div class="col-xs-5 right-aside">
                <h4>N° 0001-00000001</h4>
                <p>Fecha: @DateTime.Now.ToShortDateString()</p>
                <p>C.U.I.T: XX-XXXXXXXX-XX</p>
                <p>ING. BRUTOS: XX-XXXXXXXX-XX</p>
                <p>INICIO DE ACT.: 8/11/2013</p>
            </div>
        </div>
        <div class="row">
            <form class="form-horizontal" role="form">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Señor/es</label>
                    <div class="col-sm-10">
                        <p class="form-control-static">@Model.CustomerName</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Domicilio</label>
                    <div class="col-sm-10">
                        <p class="form-control-static">@Model.CustomerAddress</p>
                    </div>
                </div>
            </form>
        </div>
        <hr />
        <p>CONDICIONES DE VENTA</p>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>CANT.</th>
                        <th>DESCRIPCION</th>
                        <th>P. UNIT.</th>
                        <th>IMPORTE</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Quantity</td>
                            <td>@item.Description</td>
                            <td>@item.Price</td>
                            <td>@item.Total</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">TOTAL</td>
                        <td>@Model.Items.Sum(x => x.Total)</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

Source/TeamMashup.Server/Areas/Internal/Views/Billing/Details.cshtml
@using TeamMashup.Core.I18n;
@using TeamMashup.Server.Areas.Internal.Views.Billing.i18n;

@model TeamMashup.Models.Internal.BillingDetailsModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Internal/Views/Shared/_PrivateLayout.cshtml";
}

<div id="billing">
    <div class="details">

        <div class="page-header">
            <h3>@BIlling.DetailsTitle @Model.TenantName</h3>
        </div>

        <div class="table-container">
            <table id="billsTable" class="grid-control table table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>@Localized.Date</th>
                        <th>@Localized.TributaryId</th>
                        <th>@Localized.CustomerName</th>
                        <th>@Localized.CustomerAddress</th>
                        <th>@Localized.CountryName</th>
                        <th>@Localized.Items</th>
                        <th>@Localized.Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var bill in Model.Bills)
                    {
                        <tr>
                            <td><a href="@Url.Action("Bill", "Billing", new { id = bill.Id })" class="btn btn-default"><i class="icon-print"></i></a></td>
                            <td>@bill.Date</td>
                            <td>@bill.TributaryId</td>
                            <td>@bill.CustomerName</td>
                            <td>@bill.CustomerAddress</td>
                            <td>@bill.CountryName</td>
                            <td>
                                <ul>
                                    @foreach (var item in bill.Items)
                                    {
                                        <li>@item.Description</li>
                                    }
                                </ul>
                            </td>
                            <td>@bill.Price</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>

Source/TeamMashup.Server/Areas/Internal/Views/Billing/ExportBilledToExcel.cshtml
@{
    ViewBag.Title = "ExportBilledToExcel";
    Layout = "~/Areas/Internal/Views/Shared/_PrivateLayout.cshtml";
}

<h2>ExportBilledToExcel</h2>

Source/TeamMashup.Server/Areas/Internal/Views/Billing/Reports.cshtml
@using TeamMashup.Core.I18n

@model TeamMashup.Models.Internal.BillingReportModel
@{
    ViewBag.Title = "Reports";
    Layout = "~/Areas/Internal/Views/Shared/_PrivateLayout.cshtml";
}

<div id="billing">
    <div class="reports">
        <div class="page-header">
            <h1>Billing Reports <small>Subtext for header</small></h1>
        </div>

        @{Html.RenderAction("PeriodFilter");}

        <br />

        <div>
            @if (Model.Bills.Any())
            {
                <a href="@Url.Action("ExportBilledToExcel")" class="btn btn-default">Export to Excel</a>
            }
            <h3 class="pull-right">Total Billed: <span class="label label-success">@Model.TotalBilled</span></h3>
        </div>
        <br />
        <br />
        <br />
        <div class="table-container">
            <table id="reportTable" class="grid-control table table-striped">
                <thead>
                    <tr>
                        <th>@Localized.Date</th>
                        <th>@Localized.CustomerName</th>
                        <th>@Localized.TributaryId</th>
                        <th>@Localized.Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var bill in Model.Bills)
                    {
                        <tr>
                            <td>@bill.Date</td>
                            <td>@bill.CustomerName</td>
                            <td>@bill.TributaryId</td>
                            <td>@bill.Total</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

Source/TeamMashup.Server/Areas/Internal/Views/Billing/Subscriptions.cshtml
@using System.Web.Optimization
@using TeamMashup.Core.I18n;

@{
    ViewBag.Title = "Subscriptions";
    Layout = "~/Areas/Internal/Views/Shared/_PrivateLayout.cshtml";
}

@Styles.Render("~/Content/datatables")
@Scripts.Render("~/bundles/datatables")

<script type="text/javascript">

    var table;

    $(document).ready(function () {
        table = new TeamMashupDataTable({
            tableId: "subscriptionsTable",
            sourceUrl: '@Url.Action("GetSubscriptions", "Billing")',
            columns: [
                {
                    "mData": "TenantName",
                    "sTitle": "@Localized.TenantName",
                    "mRender": function (data, type, full) {
                        return "<a href='@Url.Action("Details")?tenantName=" + data + "'>" + data + "</a>";
                    }
                },
                { "mData": "CompanyName", "sTitle": "@Localized.CompanyName" },
                { "mData": "PlanName", "sTitle": "@Localized.Plan" },
                { "mData": "CountryName", "sTitle": "@Localized.Country" },
                { "mData": "State", "sTitle": "@Localized.State" },
                { "mData": "HasPendingBills", "sTitle": "@Localized.HasPendingBills" }
            ],
            rowsSelectable: false,
            showEdit: false,
            showEditInNewWindow: false,
            showDelete: false,
            showMoreOptions: false,
            enableSearch: true,
        });

    });

</script>

<div id="billing">
    <div class="subscriptions">

        <div class="page-header">
            <h3>@Localized.Subscriptions</h3>
        </div>

        <div class="table-container">
            <table id="subscriptionsTable" class="grid-control table table-striped">
                <thead>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

    </div>
</div>