Source/TeamMashup.Server/Areas/Internal/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TeamMashup.Core.Contracts;
using TeamMashup.Core.Domain;
using TeamMashup.Models.Internal;
using TeamMashup.Server.Filters;

namespace TeamMashup.Server.Areas.Internal.Controllers
{
    public class RegionController : InternalBaseController
    {
        public ActionResult Countries()
        {
            return View();
        }

        public ActionResult Languages()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult NavTabs(string activeTab)
        {
            ViewBag.ActiveTab = activeTab ?? string.Empty;
            return PartialView("_NavTabs");
        }

        [ChildActionOnly]
        public ActionResult AddCountry()
        {
            return PartialView("_AddCountry");
        }

        [ChildActionOnly]
        public ActionResult AddLanguage()
        {
            return PartialView("_AddLanguage");
        }

        public ActionResult GetCountryItems(int iDisplayStart, int iDisplayLength, string sEcho)
        {
            var query = Context.Countries.OrderByDescending(x => x.Name);

            var totalRecords = query.Count();

            var page = query.Skip(iDisplayStart).Take(iDisplayLength).ToList();

            var model = new DataTablePage
            {
                sEcho = sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords
            };

            var countries = (from x in page
                             select new CountryModel
                             {
                                 Id = x.Id,
                                 Name = x.Name
                             }).ToList();

            foreach (var country in countries)
            {
                var item = new Dictionary<string, string>
                    {
                        {"Name", country.Name},
                        {"DT_RowId", "roleItem_" + country.Id}
                    };

                model.aaData.Add(item);
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetLanguageItems(int iDisplayStart, int iDisplayLength, string sEcho)
        {
            var query = Context.Languages.OrderByDescending(x => x.Name);

            var totalRecords = query.Count();

            var page = query.Skip(iDisplayStart).Take(iDisplayLength).ToList();

            var model = new DataTablePage
            {
                sEcho = sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords
            };

            var languages = (from x in page
                             select new LanguageModel
                             {
                                 Id = x.Id,
                                 Name = x.Name,
                                 Code = x.Code
                             }).ToList();

            foreach (var language in languages)
            {
                var item = new Dictionary<string, string>
                    {
                        {"Name", language.Name},
                        {"Code", language.Code},
                        {"DT_RowId", "roleItem_" + language.Id}
                    };

                model.aaData.Add(item);
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [SetResponseStatus]
        public ActionResult AddCountry(CountryModel model)
        {
            if (ModelState.IsValid)
            {
                var country = new Country(model.Name);
                Context.AddCountry(country);

                Context.SaveChanges();
            }

            return JsonView(ModelState.IsValid,"_AddCountry", model);
        }

        [HttpPost]
        [SetResponseStatus]
        public ActionResult AddLanguage(LanguageModel model)
        {
            if (ModelState.IsValid)
            {
                var language = new Language(model.Code, model.Name);
                Context.AddLanguage(language);

                Context.SaveChanges();
            }

            return JsonView(ModelState.IsValid, "_AddLanguage", model);
        }

        public ActionResult EditCountry(long id)
        {
            Country country;
            if (!Context.Countries.TryGetById(id, out country))
                throw new InvalidOperationException(string.Format("country with id {0} was not found", id));

            var model = new CountryModel
            {
                Id = country.Id,
                Name = country.Name
            };

            return PartialView("_EditCountry", model);
        }

        public ActionResult EditLanguage(long id)
        {
            Language language;
            if (!Context.Languages.TryGetById(id, out language))
                throw new InvalidOperationException(string.Format("language with id {0} was not found", id));

            var model = new LanguageModel
            {
                Id = language.Id,
                Name = language.Name,
                Code = language.Code
            };

            return PartialView("_EditLanguage", model);
        }

        [HttpPost]
        public ActionResult EditCountry(CountryModel model)
        {
            if (ModelState.IsValid)
            {
                Country country;
                if (!Context.Countries.TryGetById(model.Id, out country))
                    throw new InvalidOperationException(string.Format("country with id {0} was not found", model.Id));

                country.Name = model.Name;
                Context.SaveChanges();
            }

            return JsonView(ModelState.IsValid, "_EditCountry", model);
        }

        [HttpPost]
        public ActionResult EditLanguage(LanguageModel model)
        {
            if (ModelState.IsValid)
            {
                Language language;
                if (!Context.Languages.TryGetById(model.Id, out language))
                    throw new InvalidOperationException(string.Format("language with id {0} was not found", model.Id));

                language.Name = model.Name;
                Context.SaveChanges();
            }

            return JsonView(ModelState.IsValid, "_EditLanguage", model);
        }

        public ActionResult DeleteCountries(long id)
        {
            return PartialView("_DeleteModalOld");
        }

        public ActionResult DeleteLanguages(long id)
        {
            return PartialView("_DeleteModalOld");
        }

        [HttpPost]
        public ActionResult DeleteCountries(long[] ids)
        {
            var countries = Context.Countries.FilterByIds(ids).ToList();
            var notDeletableCountries = countries.Where(x => Context.Subscriptions.Any(y => y.CountryId == x.Id)).ToList();

            var countriesToDelete = countries.Except(notDeletableCountries, new EntityComparer()).Cast<Country>().ToList();

            foreach (var country in countriesToDelete)
            {
                Context.Countries.Remove(country);
            }

            Context.SaveChanges();

            if (notDeletableCountries.Any())
                return JsonError("Some of the countries could not be deleted because they are in use.");

            return JsonSuccess();
        }

        [HttpPost]
        public ActionResult DeleteLanguages(long[] ids)
        {
            var languages = Context.Languages.FilterByIds(ids).ToList();
            var notDeletableLanguages = languages.Where(x => Context.UserProfiles.Any(y => y.LanguageId == x.Id)).ToList();

            var languagesToDelete = languages.Except(notDeletableLanguages, new EntityComparer()).Cast<Language>().ToList();

            foreach (var language in languagesToDelete)
            {
                Context.Languages.Remove(language);
            }

            Context.SaveChanges();

            if (notDeletableLanguages.Any())
                return JsonError("Some of the languges could not be deleted because they are in use.");

            return JsonSuccess();
        }
    }
}

Source/TeamMashup.Server/Areas/Internal/Views/Region/Countries.cshtml
@using TeamMashup.Core.I18n

@{
    ViewBag.Title = "Countries";
    Layout = "~/Areas/Internal/Views/Shared/_PrivateLayout.cshtml";
}

@Styles.Render("~/Content/datatables")
@Scripts.Render("~/bundles/datatables")

<script type="text/javascript">

    var table;
    var modal

    $(document).ready(function () {
        table = new TeamMashupDataTable({
            tableId: "countriesTable",
            sourceUrl: '@Url.Action("GetCountryItems", "Region")',
            columns: [
                { "mData": "Name", "sTitle": "@Localized.Name" },
            ],
            deleteUrl: '@Url.Action("DeleteCountries", "Region")',
            onItemDelete: function (id) {
                handleRowDelete({
                    ids: [id],
                    modalId: 'modal',
                    modal: modal,
                    displayAction: '@Url.Action("DeleteCountries", "Region")?id=' + id,
                    deleteAction: '@Url.Action("DeleteCountries", "Region")'
                });
            },
            onItemEdit: function (id, newWindow) {

                modal = $('#modal');

                modal.load('@Url.Action("EditCountry", "Region")?id=' + id, function () {
                    modal.modal();
                });
            },
            onDraw: function () {
                bindJsModals();
            },
            showEditInNewWindow: false,
            showMoreOptions: false
        });

    });

    function addCountryComplete() {
    }

    function addCountrySuccess(data) {
        addCountryContainerUpdate(data);
        table.draw();
    }

    function addCountryValidationErrors(data) {
        addCountryContainerUpdate(data);
        applyUiErrorStylesIfAny();
    }

    function addCountryContainerUpdate(data) {
        $("#addCountryContainer").html(data.View);
    }

</script>

<div id="region">
    <div class="countries">
        <div class="tabbable">

            @{ Html.RenderAction("NavTabs", new { activeTab = "Countries" }); }

            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div id="addCountryContainer">
                                @{ Html.RenderAction("AddCountry"); }
                            </div>
                        </div>

                        <div class="panel-body">
                            <div class="table-container">
                                <table id="countriesTable" class="grid-control table table-striped">
                                    <thead>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal" class="modal" role="dialog"></div>

Source/TeamMashup.Server/Areas/Internal/Views/Region/Languages.cshtml
@using TeamMashup.Core.I18n

@{
    ViewBag.Title = "Languages";
    Layout = "~/Areas/Internal/Views/Shared/_PrivateLayout.cshtml";
}

@Styles.Render("~/Content/datatables")
@Scripts.Render("~/bundles/datatables")

<script type="text/javascript">

    var table;
    var modal

    $(document).ready(function () {
        table = new TeamMashupDataTable({
            tableId: "languagesTable",
            sourceUrl: '@Url.Action("GetLanguageItems", "Region")',
            columns: [
                { "mData": "Name", "sTitle": "@Localized.Name" },
                { "mData": "Code", "sTitle": "@Localized.Code" },
            ],
            deleteUrl: '@Url.Action("DeleteLanguages", "Region")',
            onItemDelete: function (id) {
                handleRowDelete({
                    ids: [id],
                    modalId: 'modal',
                    modal: modal,
                    displayAction: '@Url.Action("DeleteLanguages", "Region")?id=' + id,
                    deleteAction: '@Url.Action("DeleteLanguages", "Region")'
                });
            },
            onItemEdit: function (id, newWindow) {

                modal = $('#modal');

                modal.load('@Url.Action("EditLanguage", "Region")?id=' + id, function () {
                    modal.modal();
                });
            },
            onDraw: function () {
                bindJsModals();
            },
            showEditInNewWindow: false,
            showMoreOptions: false
        });

    });

    function addLanguageComplete() {
    }

    function addLanguageSuccess(data) {
        addLanguageContainerUpdate(data);
        table.draw();
    }

    function addLanguageValidationErrors(data) {
        addLanguageContainerUpdate(data);
        applyUiErrorStylesIfAny();
    }

    function addLanguageContainerUpdate(data) {
        $("#addLanguageContainer").html(data.View);
    }

</script>

<div id="region">
    <div class="languages">
        <div class="tabbable">

            @{ Html.RenderAction("NavTabs", new { activeTab = "Languages" }); }

            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div id="addLanguageContainer">
                                @{ Html.RenderAction("AddLanguage"); }
                            </div>
                        </div>

                        <div class="panel-body">
                            <div class="table-container">
                                <table id="languagesTable" class="grid-control table table-striped">
                                    <thead>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal" class="modal" role="dialog"></div>

Source/TeamMashup.Server/Areas/Internal/Views/Region/_AddCountry.cshtml
@using TeamMashup.Core.I18n;
@using TeamMashup.Core;

@model TeamMashup.Models.Internal.CountryModel

@using(Ajax.CustomBeginForm("AddCountry", "addCountry", new { role = "form", @class = "form-inline" }))
{
    <div class="form-group">
        <label class="sr-only" for="name">@Localized.Name</label>
        <input type="text" id="name" name="name" class="form-control fixed-w-500" placeholder="@Localized.Name" />
        @Html.ValidationPopover("name")
    </div>
    
    <button id="add" type="submit" class="btn btn-primary">@Localized.Add</button>
}

Source/TeamMashup.Server/Areas/Internal/Views/Region/_AddLanguage.cshtml
@using TeamMashup.Core.I18n

@model TeamMashup.Models.Internal.LanguageModel

@using(Ajax.CustomBeginForm("AddLanguage", "addLanguage", new { role = "form", @class = "form-inline" }))
{
    <div class="form-group">
        <label class="sr-only" for="name">@Localized.Name</label>
        <input type="text" id="name" name="name" class="form-control fixed-w-500" placeholder="@Localized.Name" />
        @Html.ValidationPopover("name")
    </div>
    
    <div class="form-group">
        <label class="sr-only" for="code">@Localized.Code</label>
        <input type="text" id="code" name="code" class="form-control fixed-w-500" placeholder="@Localized.Code" />
        @Html.ValidationPopover("code")
    </div>
    
    <button id="add" type="submit" class="btn btn-primary">@Localized.Add</button>
}

Source/TeamMashup.Server/Areas/Internal/Views/Region/_EditCountry.cshtml
@using TeamMashup.Core.I18n
@using TeamMashup.Server.Areas.Internal.Views.Region.i18n

@model TeamMashup.Models.Internal.CountryModel

<script type="text/javascript">

    function editCountryComplete() {
    }

    function editCountrySuccess(data) {
        modal.modal('hide');
        table.draw();
    }

    function editCountryValidationErrors(data) {
        $("#modal").html(data.View);
        applyUiErrorStylesIfAny();
    }

</script>

@using (Ajax.CustomBeginForm("EditCountry", "editCountry", new { role = "form", @class = "form" }))
{
    <div class="modal-body">

        @Html.ValidationSummary(true)

        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            <label for="name">@Region.CountryName</label>
            <input type="text" id="name" name="name" value="@Model.Name" class="form-control" placeholder="@Region.EnterCountryName" />
            @Html.ValidationMessage("name", new { @class = "control-label" })
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">@Localized.Close</button>
        <button type="submit" class="btn btn-primary delete">@Localized.Save</button>
    </div>
}

Source/TeamMashup.Server/Areas/Internal/Views/Region/_EditLanguage.cshtml
@using TeamMashup.Core.I18n
@using TeamMashup.Server.Areas.Internal.Views.Region.i18n

@model TeamMashup.Models.Internal.LanguageModel

<script type="text/javascript">

    function editLanguageComplete() {
    }

    function editLanguageSuccess(data) {
        modal.modal('hide');
        table.draw();
    }

    function editLanguageValidationErrors(data) {
        $("#modal").html(data.View);
        applyUiErrorStylesIfAny();
    }

</script>

@using (Ajax.CustomBeginForm("EditLanguage", "editLanguage", new { role = "form", @class = "form" }))
{
    <div class="modal-body">

        @Html.ValidationSummary(true)

        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            <label for="name">@Region.LanguageName</label>
            <input type="text" id="name" name="name" value="@Model.Name" class="form-control" placeholder="@Region.EnterLanguageName" />
            @Html.ValidationMessage("name", new { @class = "control-label" })
        </div>

        <div class="form-group">
            <label for="code">@Region.LanguageCode</label>
            <input type="text" id="code" name="code" value="@Model.Code" class="form-control" placeholder="@Region.EnterLanguageCode" />
            @Html.ValidationMessage("code", new { @class = "control-label" })
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">@Localized.Close</button>
        <button type="submit" class="btn btn-primary delete">@Localized.Save</button>
    </div>
}

Source/TeamMashup.Server/Areas/Internal/Views/Region/_NavTabs.cshtml
@{ var activeTab = ViewBag.ActiveTab; }

<ul class="nav nav-tabs">
    <li id="countriesTab" class="@Html.Raw(activeTab == "Countries" ? "active" : string.Empty)"><a href="@Url.Action("Countries", "Region")">Countries</a></li>
    <li id="languagesTab" class="@Html.Raw(activeTab == "Languages" ? "active" : string.Empty)"><a href="@Url.Action("Languages", "Region")">Languages</a></li>
</ul>